### ISSUE TITLE
Installation of pseudo potentials fails, because server is unavailable

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-pseudo#107]
The server from which pseudo are installed (https://legacy-archive.materialscloud.org/) has an expired certificate which causes the download of the data files to fail:

```
$ aiida-pseudo install sssp -x PBE -p efficiency --download-only
Info: downloading selected pseudopotentials archive...  [FAILED]
Critical: HTTPSConnectionPool(host='legacy-archive.materialscloud.org', port=443): Max retries exceeded with url: /file/2018.0001/v4//SSSP_1.1_PBE_efficiency.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
```

The issue has already been fixed in https://github.com/aiidateam/aiida-pseudo/commit/03645e91de49ca63b431b88424b7b713c09d7169, but has not been released yet.

**Comment by sphuber** [comment]
Thanks for the report @csadorf . I have just released [v0.6.3](https://pypi.org/project/aiida-pseudo/). Let me know if the problem has not been solved.
