### ISSUE TITLE
CLI broken when installed with `aiida-core==2.1`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-pseudo#130]
This is because the CLI uses `aiida.cmdline.params.options.PROFILE` which was changed in `v2.1`. It now requires that the group/command it is associated with uses `VerdiContext` for the context class.

**Comment by unkcpz** [comment]
Hi @sphuber, any idea on how to fix this?

**Comment by sphuber** [comment]
I have already fixed it. See this branch: https://github.com/aiidateam/aiida-pseudo/tree/fix/130/cli-verdi-context
Just waiting for `aiida-core==2.1` to be released and then we can apply the fix and release it
