### ISSUE TITLE
Add PseudoDojo support with suggested cutoffs

### ISSUE THREAD

**Issue by zooks97** [aiidateam/aiida-pseudo#14]
[PseudoDojo](http://www.pseudo-dojo.org)  is a widely-used pseudopotential family developed by the Abinit team based on the ONCVPSP pseudopotential code. Despite being developed by the Abinit team (Abinit uses the psp8 format), PseudoDojo supports a variety of pseudo formats for different codes (Abinit, Q-E, Siesta):

- psp8 : (NC) the pseudo in the psp8 format (abinit)
- upf : (NC) the pseudoo in the upf format (quantum esperesso)
- psml : (NC) the pseudoo in the psml format (siesta)
- xml : (PAW) the paw dataset in xml format (abinit)

In addition to the pseudopotentials themselves, the PseudoDojo project does convergence studies with the potentials using Abinit, and they provide three suggested cutoffs (high, low, and normal) for their ONCVPSP-PBE-FR-PDv0.4 ([stringent](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PBE-FR-PDv0.4/stringent.djson), [standard](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PBE-FR-PDv0.4/standard.djson)), ONCVPSP-PBE-PDv0.4 ([stringent](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PBE-PDv0.4/stringent.djson), [standard](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PBE-PDv0.4/standard.djson)),  ONCVPSP-PBEsol-PDv0.4 ([stringent](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PBEsol-PDv0.4/stringent.djson), [standard](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PBEsol-PDv0.4/standard.djson)), and ONCVPSP-PW-PDv0.4 ([stringent](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PW-PDv0.4/stringent.djson), [standard](https://github.com/abinit/pseudo_dojo/blob/master/pseudo_dojo/pseudos/ONCVPSP-PW-PDv0.4/standard.djson)) families.

It would be good to support these in `aiida-pseudo`, but because there is both more information than the SSSP and many formats associated with these suggestions, I'm not sure how best to modify `aiida-pseudo` to support PseudoDojo and its suggestions.

**Comment by zooks97** [comment]
I've written in support for PseudoDojo by moving the suggested cutoffs support to the `PseudoPotentialFamily` class and removing it from `UpfFamily`.

I then implemented a bunch of new classes to support PseudoDojo:

- `pseudodojo.py`: `PseudoDojoFamily(PseudoPotentialFamily)`
- `pseudodojo_psp8.py`: `PseudoDojoPsp8Family(PseudoDojoFamily, Psp8Family)`
- `pseudodojo_psml.py`: `PseudoDojoPsmlFamily(PseudoDojoFamily, PsmlFamily)`
- `pseudodojo_upf.py`: `PseudoDojoUpfFamily(PseudoDojoFamily, UpfFamily)`

Finally, I added a CLI interface for downloading and installing any PseudoDojo family with the choice of `low`, `normal`, `high`, or `none` suggested cutoffs, depending on support.

**Comment by sphuber** [comment]
Fixed by PR #26
