### ISSUE TITLE
Consistent units for suggested cutoffs

### ISSUE THREAD

**Issue by zooks97** [aiidateam/aiida-pseudo#15]
Currently, the SSSP is using Ry by default as the units of its suggested cutoffs (these are the units in the metadata JSON). This is relatively ok because UPF pseudopotentials are generally used by Q-E, which uses Ry for its energy cutoff input.

PseudoDojo provides suggested cutoffs in Ha, but it also provides its pseudopotentials in various formats (UPF for Q-E, PSML for Siesta/Abinit, and PSP8 for Abinit). 

Because a variety of codes with different unit conventions are supported, I feel that we should move to a standard unit for suggested cutoffs, probably eV, so that unit problems do not crop up in the future.

**Comment by sponce24** [comment]
Abinit uses Ha, QE uses Ry and VASP uses eV. Siesta not sure?

I personally think we should use atomic unit for all units. 
This is well defined and code agnostic. This would mean Ha in this case.

**Comment by zooks97** [comment]
I suggested eV for consistency with, e.g., the` aiida-common-workflows`, where eV is the common units for the outputs.

I think that because `aiida-pseudo` will be used in conjuction with `aiida-common-workflows` by beginners who may not understand the varying unit conventions, it would be good in that case to use eV.

On the flip side, I understand that atomic units would be also a well-motivated choice. It could be good to bring this up with the `aiida-common-workflows` team, and maybe we can change the output units to be atomic units as well.

**Comment by sphuber** [comment]
I would also definitely stick to `eV` if we need a common unit, which I think is a good idea. The majority of AiiDA's ecosphere has already been maintaining `eV` as the default unit.

**Comment by bosonie** [comment]
Siesta accepts everything, we pass numbers with units attached, It knows internally how to convert them. Moreover we do not use any of the suggested suggested cutoffs, they do not apply for non PW codes. Therefore I really have no opinion on that. Happy with any choice
