### ISSUE TITLE
Add backport for SSSP v1.3 and Pseudo-Dojo v0.5

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-pseudo#156]
For the ACWF verification paper, we want to do a release to make the results fully reproducible, see

https://github.com/aiidateam/aiida-common-workflows/issues/305

This requires SSSP v1.3 and Pseudo-Dojo v0.5 to be supported in `aiida-pseudo`. This is currently the case in the latest version of `aiida-pseudo`, but the ACWF release is still for AiiDA-core v1.6.X, which is only compatible with `aiida-pseudo<0.7.0`. So we should do a backport for `aiida-pseudo` v0.6.X.

**Comment by sphuber** [comment]
Fixed by #157 and released with v0.6.5
