### ISSUE TITLE
❓Rename default branch to `main`?

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-pseudo#158]
I've gotten quite used to this being the default branch for most of the repositories I work on now, since it's the new convention. Just wanted to touch base before making the switch.

**Comment by sphuber** [comment]
And what if most repos that other contributors work on still use `master`? 😏 But sure please go ahead, happy to make your workflow a little more lightweight 😄

**Comment by mbercx** [comment]
Haha, I'm just a creature of habit, that's all. ^^ I'll rename the branch after we merge #135.
