### ISSUE TITLE
🐛  Failure to install pseudo-dojo v0.4 LDA SR standard upf 

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-pseudo#46]
I'm running into an error when trying to install the v0.4 LDA SR standard upf pseudos from the pseudo dojo. Note that the "stringent" version works fine:

```console
$ aiida-pseudo install pseudo-dojo -x LDA -f upf -p stringent
Info: downloading selected pseudo potentials archive...  [OK]
Info: unpacking archive and parsing pseudos...  [OK]
Info: downloading selected pseudo potentials metadata archive...  [OK]
Info: unpacking metadata archive and parsing metadata... [OK]
Success: installed `PseudoDojo/0.4/LDA/SR/stringent/upf` containing 70 pseudo potentials
```

But when trying the "standard" version, I get:

```console
$ aiida-pseudo install pseudo-dojo -x LDA -f upf -p standard
Info: downloading selected pseudo potentials archive...  [OK]
Info: unpacking archive and parsing pseudos...  [OK]
Info: downloading selected pseudo potentials metadata archive...  [OK]
Info: unpacking metadata archive and parsing metadata... [FAILED]
Critical: failed to parse djrepos from `/tmp/tmpqgdfjkgm`: directory `/tmp/tmpqgdfjkgm` contains djrepos with duplicate elements`
```

I'm running:
* OS: Ubuntu 18.04.5 LTS
* Python 3.8
* `aiida-pseudo==0.5.0`.

**Comment by zooks97** [comment]
Looks like they have an extra file `Ge.djrepo_old` in that djrepo archive.

**Comment by mbercx** [comment]
Thanks @zooks97! (and sorry for my slow response 😅 ) I agree it's good to fix this on our end, I'll start working on a PR. I suppose we would just check in the `PseudoDojoFamily.parse_djrepos_from_folder()` method that the `filename` extension is in a list of accepted extensions (limited to `.djrepo` so far?), and raise a warning if this isn't the case while ignoring this file?

That said, maybe also good to drop a line to the PseudoDojo guys.
