### ISSUE TITLE
Problems installing a pseudo potential family

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-pseudo#59]
Concerning the aiida-pseudo family, I have some problems during learning to use the aiida, the command "aiida-pseudo install SSSP" always fails at the third step"unpacking archives and parsing pseudos...", I downloaded the pseudo library, and extract the tar file, and with the command"verdi data upf uploadfamily path/to/folder name_of_the_family "some description for your convenience""  to create a pseudo family, however, the command "aiida-psrudo list" end up with the result"no pseudo potential families have been installed yet", why is that? I have been looking for solutions for a few days, little information could be abtained, since no instruction for install pseudo family offline at all. Could you please tell me what I missed to install the pseudo family? Thanks very much.

_Originally posted by @Angmar1989 in https://github.com/aiidateam/aiida-pseudo/issues/56#issuecomment-811651123_

**Comment by sphuber** [comment]
If you install with the old way of `verdi data upf uploadfamily` it will not create a family that `aiida-pseudo list` recognizes, that is why it doesn't find it. If you run `verdi group list` you should see it however, since the family is just a `Group`. If you want to work with `aiida-pseudo` you _have_ to install it through `aiida-pseudo install`. Can you give the exact error message when you run `aiida-pseudo install sssp`? Please run it with the `-t` option to get the full traceback.

**Comment by Angmar1989** [comment]
> If you install with the old way of `verdi data upf uploadfamily` it will not create a family that `aiida-pseudo list` recognizes, that is why it doesn't find it. If you run `verdi group list` you should see it however, since the family is just a `Group`. If you want to work with `aiida-pseudo` you _have_ to install it through `aiida-pseudo install`. Can you give the exact error message when you run `aiida-pseudo install sssp`? Please run it with the `-t` option to get the full traceback.

![QQ图片20210401150531](https://user-images.githubusercontent.com/81727429/113256411-bbcaaa80-92fb-11eb-9dac-9b87626f6c66.png)

**Comment by sphuber** [comment]
Please run with the `-t` option so `aiida-pseudo install sssp -t`

**Comment by Angmar1989** [comment]
> Please run with the `-t` option so `aiida-pseudo install sssp -t`

I found I could use command: "aiida-pseudo install family -F tar ~/SSSP_efficiency_pseudos.tar.gz sssp_1.1_efficiency" to install a downloaded tar pseudo library file, but new problems
![QQ图片20210401151904](https://user-images.githubusercontent.com/81727429/113257748-a0609f00-92fd-11eb-9540-444a7f1c65be.png)

**Comment by sphuber** [comment]
that is because you should specify which family type to use. I think the following should work
```
aiida-pseudo install family -F gztar -T pseudo.family.sssp SSSP_efficiency_pseudos.tar.gz SSSP/1.1/PBE/efficiency
```
Note that using the `SSSP/1.1/PBE/efficiency` label is very important if you want the `aiida-quantumespresso` tools to automatically detect it.

**Comment by Angmar1989** [comment]
> that is because you should specify which family type to use. I think the following should work
> 
> ```
> aiida-pseudo install family -F gztar -T pseudo.family.sssp SSSP_efficiency_pseudos.tar.gz SSSP/1.1/PBE/efficiency
> ```
> 
> Note that using the `SSSP/1.1/PBE/efficiency` label is very important if you want the `aiida-quantumespresso` tools to automatically detect it.

It works! thank you very much!!!
