### ISSUE TITLE
CLI: add possibility to download pseudo archives and metadata files without installing

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-pseudo#63]
This would be useful in the case where the automated command fails and a user needs to perform a manual install through `aiida-pseudo install family`. Here it would be good to make downloading the files as easy as possible by either providing the URLs that need to be downloaded, or by downloading them through a command (but skipping the installation part).

**Comment by mbercx** [comment]
Maybe add a `--skip-install` / `--download-only` option to the `install` commands?

**Comment by zooks97** [comment]
In the same line, it could be convenient to have a `--data-directory` flag which specifies where to download the files to (i.e. not a temporary directory). So, if a user needs to reinstall the same family at a later time for e.g. a different profile, they don't have to re-download the files each time. This would also make the MD5 checksum suggestion in #62 an even better idea as files may be corrupted or changed on disk after download and should be checked for subsequent use.

**Comment by sphuber** [comment]
The current PR adds it to the current working directory. We can add another flag in the future to add a more specific directory
