### ISSUE TITLE
CLI: `aiida-pseudo family cutoffs set` removes all other stringencies

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-pseudo#66]
Currently, the `aiida-pseudo family cutoffs set` command will take the provided `stringency` and set _only_ cutoffs for that stringency, making it the default. This means that any other stringencies will be removed from the pseudo family. I'm not sure if this is the desired behaviour, since it limits the user to only defining one stringency at a time, and could be potentially dangerous. If the user first installs a specific pseudo family with a set of recommended cutoffs, and then uses the `aiida-pseudo family cutoffs set` command when trying to add a _new_ stringency, the other recommended values will be lost.

~~Perhaps we should consider matching the `set_cutoffs` and `get_cutoffs` API's more closely. Currently their behaviour is different in the sense that the first sets _all_ cutoffs, and the second only retrieves the cutoffs for a _specified_ stringency. I must admit that this threw me off at first too. I would suggest:~~

~~* Renaming the `set_cutoffs` command to `set_cutoffs_all` or something similar.~~
~~* Adding a `set_cutoffs` command that allows the user to set the cutoffs for a single stringency.~~

~~This would also avoid awkward workarounds where in order to set a single stringency you have to get the whole dictionary with the hidden method `_get_cutoffs` (which I would consider renaming to `_get_cutoffs_dict` to make it more distinguishable from `get_cutoffs`) and then override one key and then set the cutoffs with `set_cutoffs`.~~

Second part of discussion moved to #68.

**Comment by mbercx** [comment]
@sphuber I'll put the discussion re `set_cutoffs`/`get_cutoffs` in a separate issue if you agree that the proposed changes make sense.

**Comment by sphuber** [comment]
Agree that the behavior of the CLI is a bug. I have marked it as such.

Regarding the API: I would actually just change `set_cutoffs` to only set a single stringency and make the `stringency` argument required. Don't think we actually need `set_cutoffs_all`. The fact we store it internally as a dict is an implementation detail and for a client, making a simple loop to call `set_cutoffs` multiple times should be fine. Good to split this off in a separate issue.
